name: NASA Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js version 21
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install Dependencies
        run: npm install react-scripts

      - name: Build
        run: npm run build --prefix frontend

