name: NASA Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
      MONGO_URI: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [21.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Install Dependencies
        run: npm run install

      - name: Build
        run: npm run build --prefix frontend

      
            
      
      - name: Run All Tests
        run: npm test

